name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Frontend Deployment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Angular app
      run: |
        cd YangSpaceClient
        npm install
        npm run build --prod

    - name: Deploy Angular to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_ANGULAR }}
        slot-name: 'production'
        package: YangSpaceClient/dist/yangspace

    # Backend Deployment
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build and publish ASP.NET API
      run: |
        cd YangSpaceBackEnd
        dotnet restore
        dotnet publish -c Release -o publish

    - name: Deploy ASP.NET API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_ASPNET }}
        slot-name: 'production'
        package: YangSpaceBackEnd/publish
